Fix the healtcheck script

diff --git a/healthcheck b/healthcheck
--- a/healthcheck
+++ b/healthcheck
@@ -1,72 +1,126 @@
 #!/bin/bash
 
-# set an initial value for the flag
-ARG_B=0
+readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
+readonly SCRIPT_NAME="$(basename "$0")"
 
-# read the options
-TEMP=`getopt -o abc: --long url:,clientCert:,clientCertKey:,caCert: -n 'test.sh' -- "$@"`
-eval set -- "$TEMP"
+function print_usage {
+  echo
+  echo "Usage: $SCRIPT_NAME [OPTIONS]"
+  echo
+  echo "This script is used check the health of our "
+  echo
+  echo "Options:"
+  echo
+  echo -e "  --url\t\t\tService healthcheck URL. Defaults to https://127.0.0.1:8080/actuator/healthcheck."
+  echo -e "  --clientCert\t\tClient SSL certificate. Defaults to /tmp/app.crt"
+  echo -e "  --clientCertKey\tClient SSL key. Defaults to /tmp/app.key"
+  echo -e "  --caCert\t\tCA certificate to validate service against. Defaults to /usr/local/share/ca-certificates/ascent/vault-ca.crt"
+}
 
-# extract options and their arguments into variables.
-while true ; do
-    case "$1" in
-        -a|--url)
-            case "$2" in
-                "") URL='some default value' ; shift 2 ;;
-                *) URL=$2 ; shift 2 ;;
-            esac ;;
-        -b|--clientCert)
-            case "$2" in
-                "") shift 2 ;;
-                *) CLIENT_CERT=$2 ; shift 2 ;;
-            esac ;;
-        --) shift ; break ;;
-        -c|--clientCertKey)
-            case "$2" in
-                "") shift 2 ;;
-                *) CLIENT_KEY=$2 ; shift 2 ;;
-            esac ;;
-        --) shift ; break ;;
-        -d|--caCert)
-            case "$2" in
-                "") shift 2 ;;
-                *) CA_CERT=$2 ; shift 2 ;;
-            esac ;;
-        --) shift ; break ;;
-        *) echo "Internal error!" ; exit 1 ;;
+#################################################################################################
+# UTILITY FUNCTIONS
+#################################################################################################
+
+function log {
+  local readonly level="$1"
+  local readonly message="$2"
+  local readonly timestamp=$(date +"%Y-%m-%d %H:%M:%S")
+  >&2 echo -e "${timestamp} [${level}] [$SCRIPT_NAME] ${message}"
+}
+
+function log_info {
+  local readonly message="$1"
+  log "INFO" "$message"
+}
+
+function log_warn {
+  local readonly message="$1"
+  log "WARN" "$message"
+}
+
+function log_error {
+  local readonly message="$1"
+  log "ERROR" "$message"
+}
+
+
+function assert_not_empty {
+  local readonly arg_name="$1"
+  local readonly arg_value="$2"
+
+  if [[ -z "$arg_value" ]]; then
+    log_error "The value for '$arg_name' cannot be empty"
+    print_usage
+    exit 1
+  fi
+}
+
+function assert_is_installed {
+  local readonly name="$1"
+
+  if [[ ! $(command -v ${name}) ]]; then
+    log_error "The binary '$name' is required by this script but is not installed or in the system's PATH."
+    exit 1
+  fi
+}
+
+#################################################################################################
+# CORE FUNCTIONS
+#################################################################################################
+
+function run {
+  local url="https://127.0.0.1:8080/actuator/health"
+  local clientCert="/tmp/app.crt"
+  local clientKey="/tmp/app.key"
+  local caCert="/usr/local/share/ca-certificates/ascent/vault-ca.crt"
+  local all_args=()
+
+  while [[ $# > 0 ]]; do
+    local key="$1"
+
+    case "$key" in
+      --url)
+        assert_not_empty "$key" "$2"
+        url="$2"
+        shift
+        ;;
+      --clientCert)
+        assert_not_empty "$key" "$2"
+        clientCert="$2"
+        shift
+        ;;
+      --clientCertKey)
+        assert_not_empty "$key" "$2"
+        clientKey="$2"
+        shift
+        ;;
+      --caCert)
+        assert_not_empty "$key" "$2"
+        caCert="$2"
+        shift
+        ;;
+      --help)
+        print_usage
+        exit
+        ;;
+      *)
+        log_error "Unrecognized argument: $key"
+        print_usage
+        exit 1
+        ;;
     esac
-done
 
-#STATUS=""
+    shift
+  done
 
-if [ -z "$URL" ]
-then
-  URL="https://localhost:8080/actuator/health"
-fi
+  assert_is_installed "curl"
+  local status=`curl -I -ks --stderr /dev/null  --cert $clientCert --key $clientKey --cacert $caCert $url 2>&1 | head -1 | cut -d ' ' -f2`
 
-if [ -z "$CLIENT_CERT" ]
-then
-  CLIENT_CERT="/tmp/app.crt"
-fi
+  if [ "$status" != "200" ]; then
+    curl -I -ksS --cert $clientCert --key $clientKey --cacert $caCert $url
+    log_error "Healthcheck failed. Service returned HTTP Status Code: $status"
+    exit 1
+  fi
+}
 
-if [ -z "$CLIENT_KEY" ]
-then
-  CLIENT_KEY="/tmp/app.key"
-fi
-
-if [ -z "$CA_CERT" ]
-then
-  CA_CERT="/usr/local/share/ca-certificates/ascent/vault-ca.crt"
-fi
-
-STATUS=`curl -I --stderr /dev/null  --cert $CLIENT_CERT --key $CLIENT_KEY --cacert $CA_CERT $URL 2>&1 | head -1 | cut -d ' ' -f2`
-
-#echo $STATUS
-
-if [ "$STATUS" == "200" ]
-then
- echo "0"
-else
- echo "1"
-fi
-
+run "$@"
